---
title: "LSTM 3"
author: "Annie Yang"
date: "10/10/2020"
output: 
  html_notebook:
    toc: yes
    toc_float: yes
---

# 1.0 Libraries

```{r, warning=FALSE}
# Core Tidyverse
library(tidyverse)
library(glue)
library(forcats)

# Time Series
library(timetk)
library(tidyquant)
library(tibbletime)

# Visualization
library(cowplot)

# Preprocessing
library(recipes)

# Sampling / Accuracy
library(rsample)
library(yardstick) 

# Modeling
library(keras)
```

# 2.0 Data

```{r, warning=FALSE}
df <-  read.csv("D:/IIT-master/CS-571-Data Preparation & Analysis-master/project/diabetes_ds/sample_dat.csv", sep=",", header=T, stringsAsFactors = T)

value <- df$IMPUTED

db.date <- paste0(df$YEAR,'-',df$MONTH,'-',df$DAY)
db.time <- paste0(df$HOUR,':',df$MIN,':',df$SEC)


cgm_data <- data.frame(value)
cgm_data$index <-as.POSIXct(paste(db.date, db.time), format="%Y-%m-%d %H:%M:%S")

#Re-ordered
cgm_data <- cgm_data[colnames(cgm_data)[c(2, 1)]]

cgm_data <- as_tbl_time(cgm_data, index = index)


cgm_data
```


# 3.1 Developing A Backtesting Strategy

```{r, warning=FALSE, echo=FALSE}
periods_train <- 12*24*2 # 1 week
periods_test  <- 12*6 # 2 hours
skip_span     <- 12 * 24

rolling_origin_resamples <- rolling_origin(
    cgm_data,
    initial    = periods_train,
    assess     = periods_test,
    cumulative = FALSE,
    skip       = skip_span
)

rolling_origin_resamples
```

# 5.0 Modeling The Keras Stateful LSTM Model

#5.1 Single LSTM
```{r}
split    <- rolling_origin_resamples$splits[[23]]
split_id <- rolling_origin_resamples$id[[23]]
```

# 5.1.2 Data Setup
```{r, warning=FALSE}
df_trn <- training(split)
df_tst <- testing(split)
df <- bind_rows(
    df_trn %>% add_column(key = "training"),
    df_tst %>% add_column(key = "testing")
) %>% 
    as_tbl_time(index = index)
df
```

# 5.1.3 Preprocessing With Recipes
```{r}
rec_obj <- recipe(value ~ ., df) %>%
    step_sqrt(value) %>%
    step_center(value) %>%
    step_scale(value) %>%
    prep()
df_processed_tbl <- bake(rec_obj, df)
df_processed_tbl
```

```{r}
center_history <- rec_obj$steps[[2]]$means["value"]
scale_history  <- rec_obj$steps[[3]]$sds["value"]
c("center" = center_history, "scale" = scale_history)
```

# 5.1.4 LSTM Plan
```{r}
# Model inputs
lag_setting  <- nrow(df_tst)
batch_size   <- 24
train_length <- 12*24
tsteps       <- 1
epochs       <- 300
```

# 5.1.5 2D And 3D Train/Test Arrays
```{r}
# Training Set
lag_train_tbl <- df_processed_tbl %>%
    mutate(value_lag = lag(value, n = lag_setting)) %>%
    filter(!is.na(value_lag)) %>%
    filter(key == "training") %>%
    tail(train_length)
x_train_vec <- lag_train_tbl$value_lag
x_train_arr <- array(data = x_train_vec, dim = c(length(x_train_vec), 1, 1))
y_train_vec <- lag_train_tbl$value
y_train_arr <- array(data = y_train_vec, dim = c(length(y_train_vec), 1))
# Testing Set
lag_test_tbl <- df_processed_tbl %>%
    mutate(
        value_lag = lag(value, n = lag_setting)
    ) %>%
    filter(!is.na(value_lag)) %>%
    filter(key == "testing")
x_test_vec <- lag_test_tbl$value_lag
x_test_arr <- array(data = x_test_vec, dim = c(length(x_test_vec), 1, 1))
y_test_vec <- lag_test_tbl$value
y_test_arr <- array(data = y_test_vec, dim = c(length(y_test_vec), 1))
```

# 5.1.6 Building The LSTM Model
```{r, warning=FALSE}
model <- keras_model_sequential()
model %>%
    layer_lstm(units            = 100, 
               input_shape      = c(tsteps, 1), 
               batch_size       = batch_size,
               return_sequences = TRUE, 
               stateful         = TRUE) %>% 
    layer_lstm(units            = 50, 
               return_sequences = FALSE, 
               stateful         = TRUE) %>% 
    layer_dense(units = 1)
model %>% 
    compile(loss = 'mae', optimizer = 'adam')
model
```

# 5.1.7 Fitting The LSTM Model
```{r}
for (i in 1:epochs) {
    model %>% fit(x          = x_train_arr, 
                  y          = y_train_arr, 
                  batch_size = batch_size,
                  epochs     = 1, 
                  verbose    = 1, 
                  shuffle    = FALSE)
    
    model %>% reset_states()
    cat("Epoch: ", i)
    
}
```

# 5.1.8 Predicting Using The LSTM Model
```{r, warning=FALSE}
# Make Predictions
pred_out <- model %>% 
    predict(x_test_arr, batch_size = batch_size) %>%
    .[,1] 
# Retransform values
pred_tbl <- tibble(
    index   = lag_test_tbl$index,
    value   = (pred_out * scale_history + center_history)^2
) 
# Combine actual data with predictions
tbl_1 <- df_trn %>%
    add_column(key = "actual")
tbl_2 <- df_tst %>%
    add_column(key = "actual")
tbl_3 <- pred_tbl %>%
    add_column(key = "predict")
# Create time_bind_rows() to solve dplyr issue
time_bind_rows <- function(data_1, data_2, index) {
    index_expr <- enquo(index)
    bind_rows(data_1, data_2) %>%
        as_tbl_time(index = !! index_expr)
}
ret <- list(tbl_1, tbl_2, tbl_3) %>%
    reduce(time_bind_rows, index = index) %>%
    arrange(key, index) %>%
    mutate(key = as_factor(key))
ret
```

# 5.1.9 Assessing Performance Of The LSTM On A Single Split
```{r}
calc_rmse <- function(prediction_tbl) {
    
    rmse_calculation <- function(data) {
        data %>%
            spread(key = key, value = value) %>%
            select(-index) %>%
            filter(!is.na(predict)) %>%
            rename(
                truth    = actual,
                estimate = predict
            ) %>%
            rmse(truth, estimate)
    }
    
    safe_rmse <- possibly(rmse_calculation, otherwise = NA)
    
    safe_rmse(prediction_tbl)
        
}
```

```{r}
calc_rmse(ret)$.estimate
```

# 5.1.10 Visualizing The Single Prediction
```{r}
# Setup single plot function
plot_prediction <- function(data, id, alpha = 1, size = 2, base_size = 14) {
    
    rmse_val <- calc_rmse(data)$.estimate
    
    g <- data %>%
        ggplot(aes(index, value, color = key)) +
        geom_point(alpha = alpha, size = size) + 
        theme_tq(base_size = base_size) +
        scale_color_tq() +
        theme(legend.position = "none") +
        labs(
            title = glue("{id}, RMSE: {round(rmse_val, digits = 1)}"),
            x = "", y = ""
        )
    
    return(g)
}
```

```{r}
ret %>% 
    plot_prediction(id = split_id, alpha = 0.5) +
    theme(legend.position = "bottom")
```

